#!/bin/sh
set -e

# Update `myhostname` in Postfix in order to send emails
postconf -e myhostname=$(hostname)

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"

