#!/bin/bash
set -e

# Update `myhostname` in Postfix in order to send emails
postconf -e myhostname=$(hostname)

if [ "$ENV" != "prod" ]; then
    echo "Environment is set to DEV"

    # Diable Opcache
    echo "[ opcache ] Configuring dev mode"
    sed -i "s/opcache.revalidate_freq\s*=\s*[[:digit:]]\+/opcache.revalidate_freq=0/" /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

    # Enable Blackfire
    echo "[ blackfire ] Enabling Blackfire"
    sed -i "s/^;//" /usr/local/etc/php/conf.d/blackfire.ini

    # Enable XDebug
    echo "[ xdebug ] Enabled"
    sed -i "1s/^;//" /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    if [ -z "$XDEBUG_CLIENT_HOST" ]; then
        if [ -n "$(dig +short host.docker.internal)" ]; then
            # MacOS
            XDEBUG_CLIENT_HOST=$(dig +short host.docker.internal)
        else
            # Linux
            XDEBUG_CLIENT_HOST=$(ip route show | awk '/default/ {print $3}')
        fi
    fi
    echo "[ xdebug ] Set client host to $XDEBUG_CLIENT_HOST"

    sed -i "s/xdebug.client_host\s*=\s*.*/xdebug.client_host=$XDEBUG_CLIENT_HOST/" /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    if [ -n "$XDEBUG_CLIENT_PORT" ]; then
        echo "[ xdebug ] Set client port to $XDEBUG_CLIENT_PORT"
        sed -i "s/xdebug.client_port\s*=\s*.*/xdebug.client_port=$XDEBUG_CLIENT_PORT/" /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    fi

    if [ -n "$XDEBUG_START_WITH_REQUEST" ]; then
        echo "[ xdebug ] Set xdebug.remote_autostart to $XDEBUG_START_WITH_REQUEST"
        sed -i "s/xdebug.start_with_request\s*=\s*.*/xdebug.start_with_request=$XDEBUG_START_WITH_REQUEST" /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    fi
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"

